language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Ez4lmAG0xgYA9L+ynCIaSjEpNHTfGV0as6Eea2+K7wV7wblQnOnBuohde5lg6lbjvaICkT/ZhiXv03O1Y4OfD/D+pX3jTvWLRD+w0AkvpTrqUIcKTNzSkcpLy12bm6TCcl/JqitteXNfgANypAgO9+w8T6DCa76+TvM9iAngqovxSrKyakPfGVzbvjTYZBVpXF4a86b6qWkaYCGcsDDqpgbHGQnlWrlXEzq+h3Msr2Ca7hPZK1xvGXd2Riu2jV0a8XqK7F1NRF98nGODvuKpg42Y2nAYyyD5b2Nb4CGc0yvobNxQ79n+Xs30iMAMiK+pqVQQOgwVegrpcidlqHUkch9hNzGzRF/AGGGy/Q+yRH4RKKz6kHXUMCdTlHVUk4wHA10WEMeWT3yG7pPdS/pG8YqUxhpnwWzuBR3jeMY5XwP+tfKdx7L7u20xWB8Q5Pde6+rqGcDRI94TNfpbHvEE1qUq3oT2u1FG6Wd9VhDjxtKXmwdqmd8awKB9WV8mCnZDU+efjCRcj1lp+N06Guxj+QqXxAQBfdg/ETaBIV9tnnlVyhM96GhcGfKX2ortdsvnF/U/j6ViK53LuENy8YkVwmnMv/pivAuF0vqcJEso15J5nQ1n9UNNGYcSw+RU2qvzk0Iq08uWFJOY3F7hrTU2mVq2BEs6VmCU5tCAvUHMTR8="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "eddiehorng/libelf"
      description: "Build submitted via Travis CI"
    notification_email: eddiehorng.tw@gmail.com
    build_command_prepend: "make nuke"
    build_command: "make"
    branch_pattern: master

script:
  - make nuke
  - make
